import './globals.css'
import type { Metadata } from 'next'
import Modal from '@/app/Components/Modal'

export const metadata: Metadata = {
  title: 'Trello Clone',
  description: 'Generated by Pratik Valvi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Modal />
      </body>
    </html>
  )
}
